import Join from "@/components/join/join";
import LayoutForAfterSplash from "@/components/layout/layout";
import Splash from "@/components/splash/splash";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [splash, setSplash] = useState(true);
  useEffect(() => {
    const timeOut = setTimeout(() => {
      setSplash(false);
    }, 3500);
    return () => clearTimeout(timeOut);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Splash on={splash} />
      <LayoutForAfterSplash
        className="text-main_blue font-semibold"
        link="/login"
        label={"Log In"}
        on={splash}
      >
        <Join />
      </LayoutForAfterSplash>
    </>
  );
}
